-- Reference schema for the UNO game-history database (H2 dialect).
--
-- NOTE: This file is documentation only. At runtime the application relies on
-- Hibernate auto-DDL (hibernate.hbm2ddl.auto=update) to create/update these
-- tables, so you do not need to run this script manually. It mirrors the JPA
-- entities in the `persistence` package.

CREATE TABLE IF NOT EXISTS player (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS game (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at       TIMESTAMP NOT NULL,
    ended_at         TIMESTAMP,
    winner_player_id BIGINT REFERENCES player (id),
    rounds_played    INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS round (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id          BIGINT NOT NULL REFERENCES game (id),
    round_number     INTEGER NOT NULL,
    winner_player_id BIGINT REFERENCES player (id)
);

CREATE TABLE IF NOT EXISTS score (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id  BIGINT NOT NULL REFERENCES round (id),
    player_id BIGINT NOT NULL REFERENCES player (id),
    points    INTEGER NOT NULL
);
